### ISSUE TITLE
Remove SFGI stuff

### ISSUE THREAD

**Issue by ItsiW** [ItsiW/VILF#10]

**Comment by schradert** [comment]
@ItsiW what do you want to remove?

**Comment by ItsiW** [comment]
There's some logic around leaving a something going for it (should be sgfi), where there is an extra field in the .md file and it gets displayed only in certain locations.

e.g. https://vilf.org/places/toss-noodle-bar/
Something Going For It — tasty fried noodles

I think it's best if all this stuff is removed, including the extra sgfi field where it exists
